name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        cd lang
        cargo test --verbose
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for Linux
      run: |
        cd lang
        cargo build --release --verbose
    
    - name: Setup for Windows
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        rustup toolchain install nightly
        rustup default nightly
        rustup target add x86_64-pc-windows-gnu

    - name: Build for Windows
      run: |
        cd lang
        cargo build --release --verbose --target x86_64-pc-windows-gnu

    - name: Setup for macOS
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Build for macOS (Intel)
      run: |
        cd lang
        cargo build --release --verbose --target x86_64-apple-darwin

    - name: Build for macOS (Apple Silicon)
      run: |
        cd lang
        cargo build --release --verbose --target aarch64-apple-darwin

    - name: Prepare binaries
      run: |
        mkdir -p artifacts
        cp lang/target/x86_64-pc-windows-gnu/release/modu.exe artifacts/modu.exe
        cp lang/target/release/modu artifacts/modu-linux
        cp lang/target/x86_64-apple-darwin/release/modu artifacts/modu-macos-intel
        cp lang/target/aarch64-apple-darwin/release/modu artifacts/modu-macos-arm64

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: artifacts/*